# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ node ]
  pull_request:
    branches: [ node ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      working-directory: examples/node/gift_giver
    - run: yarn build
      working-directory: examples/node/gift_giver
    - run: yarn test:all
      working-directory: examples/node/gift_giver
      env:
        CI: true
        DB_STORAGE: ":memory:"
        DB_DIALECT: sqlite
